### ISSUE TITLE
Boot GUI

### ISSUE THREAD

**Issue by iondarie** [xapenny/E3v2-Catalina-Hackintosh-setup#1]
Hello,

I am running allmost the same hardware as you but i have one small question how did you enable the BOOT GUI?

Thank you,

**Comment by xapenny** [comment]
1:Use latest OpenCore 0.5.7 beta
2:Edit config.plist using OCC(version>=1.19.00). Go to Misc->Picker Mode, select "built-in".
3.Enable ShowPicker and change Timeout other than 0.
4:Copy 'Icons' folder to /EFI/OC
5:Reboot and have fun.

PS: If you want to set a photo as background, you can add background.png (or background4k.png  depends on your monitor's resolution) to /EFI/OC/Icons

**Comment by iondarie** [comment]
hello again, 

i forgot to ask does your sleep/wake work?

Mine goes to sleep, but on wake-up the login screen is frozen.

**Comment by xapenny** [comment]
Works but I have it disabled cuz it will break my Apple Watch unlock.

To solve your problem, you have to add VoodooTSCSync.kext to EFI/OC/Kexts
